name: Build and Test

on:
  push:
    branches: [master, neffets]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          clean: true
          lfs: true

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle update
          rake rdoc
          gem build redmine_plugin_support.gemspec
